{{- $fqdn := printf "%s.%s" .Values.tailscale.hostname .Values.tailscale.tailnet -}}
{{- $altNames := list
    "certctl"
    (printf "certctl.%s" .Release.Namespace)
    (printf "certctl.%s.svc" .Release.Namespace)
    (printf "certctl.%s.svc.cluster.local" .Release.Namespace)
    $fqdn
-}}
{{- $cert := genSelfSignedCert $fqdn nil $altNames 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: certctl-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}