stages:
  - sync
  - build
  
variables:
  IMAGE_NAME: ghcr.io/hou85/certctl-server

build_image:
  stage: build
  image: docker:27
  services:
    - docker:27-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo "$GHCR_TOKEN" | docker login ghcr.io -u hou85 --password-stdin

  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

sync_to_github:
  stage: sync
  image: alpine:3.22

  before_script:
    - apk add --no-cache git openssh-client rsync

    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519

    - ssh-keyscan github.com >> ~/.ssh/known_hosts

    - echo "SSH KEY OK:"
    - head -1 ~/.ssh/id_ed25519

    - ssh -i ~/.ssh/id_ed25519 -T git@github.com || true

    - git config --global user.email "gitlab-ci@local"
    - git config --global user.name "GitLab CI"

  script:
    - git clone git@github.com:hou85/certctl.git out

    - rsync -av --delete ./ out/ --exclude .git

    - cd out

    - git add .

    - |
      git diff --cached --quiet \
      && echo "No changes" \
      || git commit -m "sync from gitlab"

    - git push origin main